image: golang
env:
    - PATH=$PATH:/usr/local/go/bin
    - GOPATH=/luetbuild/go
    - GO111MODULE=on
    - CGO_ENABLED=0
    - LDFLAGS="-s -w"
prelude:
    - |
      PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
      mkdir -p /luetbuild/go/src/github.com/rancher-sandbox && cd /luetbuild/go/src/github.com/rancher-sandbox && \
      git clone https://github.com/rancher-sandbox/luet-mtree && cd luet-mtree && git checkout "v${PACKAGE_VERSION}" -b build
steps:
  - |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    cd /luetbuild/go/src/github.com/rancher-sandbox/luet-mtree && make build && mv bin/luet-mtree /usr/bin/luet-mtree
includes:
  - /usr/bin/luet-mtree